name: wooribank_error_remittance
description: 편리한 착오송금 반환 서비스

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_native_splash: ^1.2.1
  flutter_screenutil: ^5.0.0+2
  flutter_test:
    sdk: flutter

flutter:
#  uses-material-design: true
   assets:
     - assets/ic_launcher.png
     - assets/wooribank_logo.png
     - assets/icons/face_id.png
     - assets/icons/person_outline.png

flutter_native_splash:
  image: assets/ic_launcher.png # size: 900x900
  color: "FFFFFF"